### ISSUE TITLE
[BUG] Night Vision Module On Helmet Crashed client

### ISSUE THREAD

**Issue by Nidre** [GabrielOlvH/Industrial-Revolution#107] opened 2021-02-13 13:41 UTC
**Description:**
Night Vision Module On Helmet Crashed client

**Steps to Reproduce:**
Craft module helmet, upgrade it night vision

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.30.0
 - Industrial Revolution: 1.7.15-BETA

**Logs:**
[crash-2021-02-13_14.26.48-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/5975737/crash-2021-02-13_14.26.48-client.txt)

**Comment by GabrielOlvH** [comment] 2021-02-13 18:21
That does not look like it was caused by indrev, the handler name from the crash is different from what it uses. Try to reproduce this crash with https://github.com/comp500/mixintrace/releases/tag/1.0.0 to find all mixins in that class.

**Comment by Nidre** [comment] 2021-02-14 12:57
[crash.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/5977720/crash.txt)

**Comment by GabrielOlvH** [comment] 2021-02-14 13:51
The conflict is with the Fabrication mod. I explain more about it [here](https://github.com/unascribed/Fabrication/blob/cda70e5ab251e6bb2e7a15954e578cce1d6f6758/src/main/java/com/unascribed/fabrication/support/MixinConfigPlugin.java#L63). You can try disabling the `.no_night_vision_flash` config temporarily to solve this issue, but this conflict will be fixed in indrev's next update.

**Closed** 2021-02-16 23:51 UTC
Labels: bug
