### ISSUE TITLE
[BUG] Compatibility with Wireless Chargers by SuperMartijn642 

### ISSUE THREAD

**Issue by Teboran** [GabrielOlvH/Industrial-Revolution#547] opened 2023-08-15 19:30 UTC
**Description:**
- Server crashes when Chargers are connected to IndRev cables

**Steps to Reproduce:**
- Attach a wireless charger to an IndRev cable
**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: 0.76.0+1.19.2
 - Industrial Revolution: 1.15.1-beta
 - Modpack: All of Fabric 1.9.1

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.
[crash-2023-08-15_15.15.37-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/12352418/crash-2023-08-15_15.15.37-server.txt)

**Comment by GabrielOlvH** [comment] 2023-08-16 15:01
Thanks for reporting, but this looks like an issue that is already fixed in the 1.20 versions. Unfortunately I won't maintain older versions. If you can reproduce on 1.20, please open a new issue.

**Closed as completed by GabrielOlvH** 2023-08-16 15:01 UTC
Labels: bug
