### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rekkep** [GabrielOlvH/Industrial-Revolution#38] opened 2020-09-17 16:31 UTC
The rancher will feed baby cows

**Comment by GabrielOlvH** [comment] 2020-09-18 12:48
This is actually an intended behaviour but I see why it may not be desirable. I'll look into adding more customization to the rancher for a future update so you can toggle some things like this one. I'll close the issue for now but thanks for bringing it up!

**Closed by GabrielOlvH** 2020-09-18 12:48 UTC
