### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Pumpkin8678** [GabrielOlvH/Industrial-Revolution#300] opened 2021-08-21 14:43 UTC
#300 My game crashes before launching the game, i try it even with only Industrial evolution mod but it still crashed.

**Comment by wootaboot** [comment] 2021-08-23 04:05
hasnt been updated to use the latest fabric API, I'm using 0.37.1, not 0.38.2

**Comment by GabrielOlvH** [comment] 2021-08-29 22:32
Duplicate of #301

**Closed by GabrielOlvH** 2021-08-29 22:32 UTC
