### ISSUE TITLE
High frame time when looking at Chopper tree farm

### ISSUE THREAD

**Issue by gharris1727** [GabrielOlvH/Industrial-Revolution#40] opened 2020-09-25 09:16 UTC
Hi,

I'm experiencing high frame times and visual jitters that seem to be related to the Chopper. Here's an example Alt-F3 graph while i'm experiencing the issue, with the red spikes corresponding to the Chopper breaking a block:
![2020-09-25_01 55 25](https://user-images.githubusercontent.com/5856969/94248617-95066400-fed3-11ea-9969-ffcd97149b98.png)

I played around with it and learned that the spikes:
* Improve when facing away from the chopper/trees
* Disappear when sufficiently far from the chopper/trees (~20 blocks)
* Are not affected by the fast/fancy/fabulous graphics setting
* Are not affected by the smooth lighting setting
* Are not affected by the particles setting
* Are not affected by the mipmapping setting

I'm using 1.6.6-BETA included in the [All Of Fabric 3 2.0.5](https://github.com/TeamAOF/All-of-Fabric-3) modpack.
Can anyone else confirm this behavior? I think I will need to relocate the farm to avoid the lag :(

**Comment by GabrielOlvH** [comment] 2020-09-25 11:41
This might be a long shot but updating to the latest version of AOF might fix this, please let me know if it does

**Comment by gharris1727** [comment] 2020-09-26 03:23
I tried out AOF3 2.1.1 / indev-1.6.11-BETA and i'm still getting the spikes.

**Comment by GabrielOlvH** [comment] 2020-09-26 14:22
Thanks for the info, I'll investigate and see what I can find!

**Comment by GabrielOlvH** [comment] 2020-09-26 16:26
I need some more information if possible:
 1. Is the Chopper getting consistent amount of energy to keep the flow or does it keep running out of energy?
 2. How fast is it breaking blocks?
 3. If you remove everything but the Axe (remove bone meals and saplings) from the input does this keep happening?

Is it also possible for you to provide a download for your world?

**Comment by GabrielOlvH** [comment] 2020-10-03 21:52
I can't reproduce this and there isn't enough information for me to look further into it. As there's been no other reports about this so far I'll be closing this but feel free to reply again with more information and I'll reopen the issue.

**Closed by GabrielOlvH** 2020-10-03 21:52 UTC
Labels: bug, can't reproduce, invalid
