### ISSUE TITLE
[1.16.2] Installing this mod with 'KubeJS-Fabric' causes custom recipes not to load properly.

### ISSUE THREAD

**Issue by Gbergz** [GabrielOlvH/Industrial-Revolution#34] opened 2020-09-03 22:29 UTC
Title^
Adding recipes through KubeJS with this mod installed makes the recipes added not work,  but after a '**/reload**' it works like 25% of the time.
Also the recipes added gets added shown twice in REI. That is when a recipe added do work which it likely won't. 
It's really hard to explain this but essentially when I load into a world and check for a custom recipe, it sometimes doesn't load. And if it loads (which is rare), it gets shown twice in REI. But then after a '**/reload**' or relog the recipe is gone again.

This doesn't happen when the mod is removed. 
Meaning everything works as intended if this mod is removed.

**Example of double REI recipes:**
![image](https://user-images.githubusercontent.com/26634554/92179174-79fc8300-ee44-11ea-9a61-1290df0e705e.png)

### Versions:
**Minecraft:** 1.16.2
**Fabric API:** 0.19.0+build.398-1.16
**IndRev:** 1.6.2-BETA
**KubeJS:** 1.4.1

**Other information:**
This is reproducable for me on an empty instance with only Fabric API, Fabric Language Kotlin & KubeJS. And ofcourse Industrial Revolution. With a custom recipe.

**-** Gbergz

**Comment by GabrielOlvH** [comment] 2020-09-03 22:32
Is there any log output that could be related to this?

**Comment by Gbergz** [comment] 2020-09-03 22:40
I've been sitting trying to figure out what could be causing it for like 3 hours now. Logs say nothing. I've gotten help by AK9 and we're both unsure. Until I decided to remove a mod 1 by 1 until the problem went away.

**Comment by GabrielOlvH** [comment] 2020-09-03 22:47
Can you please test if the issue is fixed with [this](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3049166) version?

**Comment by Gbergz** [comment] 2020-09-03 22:51
Just tried it, same issue persists unfortunately.

**Comment by Katorone** [comment] 2020-09-03 22:53
In your log, are you seeing errors similar to these? https://github.com/KubeJS-Mods/KubeJS-Fabric/issues/3
But pertaining to industrial revolution?

**Comment by Gbergz** [comment] 2020-09-03 22:54
> In your log, are you seeing errors similar to these? [KubeJS-Mods/KubeJS-Fabric#3](https://github.com/KubeJS-Mods/KubeJS-Fabric/issues/3)
> But pertaining to industrial revolution?

Yes but only this line:
``[ForkJoinPool.commonPool-worker-3/WARN]: Parsing error loading recipe techreborn:centrifuge/calciumcarbonate_cell
net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: {fluid:"techreborn:calcium_carbonate",holder:"techreborn:cell"}``

**Comment by GabrielOlvH** [comment] 2020-09-03 23:04
It's strange that it happens even without AE2 and TechReborn which is what I add compatibility recipes for. If you don't add any custom recipes does everything work as expected?

**Comment by Gbergz** [comment] 2020-09-03 23:08
Recipes work like normal if there are no custom recipes available.

**Comment by GabrielOlvH** [comment] 2020-09-04 01:20
I tried tracking this but could not find anything. This is possibly a KubeJS issue, I'd recommend opening an issue on their repository. If it ends up being an issue on my end, I'll happily fix it!

**Comment by GabrielOlvH** [comment] 2020-09-04 21:27
This should be fixed in the latest version of KubeJS, thanks for the report!

**Closed by GabrielOlvH** 2020-09-04 21:27 UTC
Labels: bug, invalid
