### ISSUE TITLE
[BUG] Shearing Sheeps work - but do not collect wool

### ISSUE THREAD

**Issue by hugeblank** [GabrielOlvH/Industrial-Revolution#196] opened 2021-05-25 00:21 UTC
**Description:**
Sheeps get properly sheared, however instead of the wool going into the rancher output like expected, it just drops on the ground

**To Reproduce:**
Set up a rancher with power & shears near a sheep

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: v0.34.2
 - Industrial Revolution: v1.9.9

**Comment by GabrielOlvH** [comment] 2021-05-26 12:56
I cannot reproduce this issue

**Comment by hugeblank** [comment] 2021-05-26 23:06
Yeah I'm using vanilla shears, I'll try and provide you a video later today.

**Comment by GabrielOlvH** [comment] 2021-05-27 12:07
A list of mods would also be helpful, might be a conflict.

**Comment by hugeblank** [comment] 2021-05-27 12:12
Here's the full list, pulled from a crash report:
```
		adorn: Adorn 1.13.0+1.16.5
		ae2wtlib: AE2WTLib 1.0.7-beta.1
		alloy_forgery: Alloy Forgery 1.0.8
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.2.0-alpha.3
		architectury: Architectury 1.12.145
		artifice: Artifice 0.13.2+1.16.3
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bagels_baking: Bagel's Baking 0.3.3
		bambootweaks: Bamboo Tweaks 2.0.5
		battletowers: Battle Towers 3.3.4-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.7
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.0
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.8.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.0
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.0
		cardinal-components-level: Cardinal Components API (world saves) 2.8.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-util: Cardinal Components API (utilities) 2.8.0
		cardinal-components-world: Cardinal Components API (worlds) 2.8.0
		carpet: Carpet Mod 1.4.34
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleardespawn: Clear Despawn 1.16.5-fabric0.30.0-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.4.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		computercraft: CC:T for Fabric 1.94.0
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		craftpresence: CraftPresence 1.8.1
		crowdin-translate: CrowdinTranslate 1.2
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		durabilityviewer: Giselbaers Durability Viewer 1.16.5-fabric0.30.0-1.10
		dynamicfps: Dynamic FPS 2.0.1
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		enchant_giver: Enchant Giver 1.0.3
		extraalchemy: Extra Alchemy 1.4.4
		extraorigins: Extra Origins 1.16.5-11
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fasttransferlib: Fast Transfer Lib 0.3.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		glassdoor: Glass Doors 1.5.0-1.16
		hydrogen: Hydrogen 0.2
		indium: Indium 1.0.0
		indrev: Industrial Revolution 1.9.9-BETA
		inmis: Inmis 2.2.1-1.16.5
		inventorysorter: Inventory Sorter 1.7.9-1.16
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.7
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.4
		magna: Magna 0.2.1-1.16.5
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		mixintrace: MixinTrace 1.0.0
		mo_glass: Mo Glass 1.5-MC1.16.4
		moborigins: Mob Origins 1.4.0
		modmenu: Mod Menu 1.16.9
		monster-in-the-closet: Monsters in the Closet 1.0.0
		mooblooms: Mooblooms 1.4.0
		mostructures: Mo' Structures 1.1.0+mc.1.16.5
		multi_item_lib: Multi Item Lib 1.2.0
		mythicmetals: Mythic Metals 0.9.9
		nbtcrafting: NBT Crafting 2.0.11+mc1.16.4
		netherite_plus: Netherite Plus Mod 1.4.3-1.16.5
		notenoughcrashes: Not Enough Crashes 3.2.0
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.1
		origins-classes: Origins: Classes 1.1.1
		originsumbrellas: Origins: Umbrellas 1.1.0
		oro_config: OroArmor Config 2.0.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		phonos: Phonos 0.1.1-beta
		phosphor: Phosphor 0.7.2+build.12
		piglib: Piglib 1.0.3+1.16.5
		ping: Ping 1.2.1
		playerabilitylib: Pal 1.2.1
		quickshulker: Quick Shulker 1.1.14-1.16
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.2+build.132
		requiem: Requiem 1.7.4
		requiemapi: Requiem-API 1.7.4
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		roughlyenoughresources: Roughly Enough Resources 2.1.4
		satin: Satin 1.5.1
		shulkerutils: shulkerutils 1.0.1-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		sodium: Sodium 0.1.1+rev.6caf15f
		spellbound: Spellbound 1.2.1
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		strawgolem: Strawgolem 1.9.4
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.3+build.231
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		toomanyorigins: TooManyOrigins 0.1.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210303.123654
		voicechat: Simple Voice Chat 1.16.5-1.2.1
		voxelmap: VoxelMap 1.10.15
		waila: Hwyla 1.9.22
		whereisit: Where Is It 1.11.7
		yungsapi: YUNG's API 1.16.5-Fabric-2
```
Also here's a screenshot of the wool popping off the sheep without being collected:
![image](https://user-images.githubusercontent.com/16393543/119823742-0571e480-beaa-11eb-8029-defdf6b3211d.png)
I feel like a screenshot is probably enough evidence in this case

**Comment by hugeblank** [comment] 2021-05-27 23:50
okay yeah this doesn't happen with just indrev. Is there an easy way to track which mod would be interrupting the collection process of the machine?

**Comment by MCrafterzz** [comment] 2021-05-28 05:32
You canways binary search it aka remove half of the mods. Does it still not happen then add half of the removed ones back otherwise remove half of the current ones. Continue doing this until you only have one mod left

**Comment by GabrielOlvH** [comment] 2021-06-13 18:44
Closing since it's not an issue in the mod itself and since in 1.17 the loot collection part was changed

**Closed by GabrielOlvH** 2021-06-13 18:44 UTC
Labels: bug, mod incompatibility
