### ISSUE TITLE
[BUG] Ticking block entity crash, flux container issue?

### ISSUE THREAD

**Issue by Wolfox-Wolf** [GabrielOlvH/Industrial-Revolution#433] opened 2022-03-28 18:13 UTC
The problem seems to be at the lazuli flux container mk3 mentioned in the log, but I am not sure how so.

I'm not sure what is causing the issue, and I do not know if it is easily reproducible. This is a text breakdown of all connected machines via wire network:

**Main network:** 4 mk3 solar panels -> 4 lifts and 4 screens -> 2 biofuel generators -> flux container mk3 -> flux container mk2

**Flux container mk3 output:** mk1 farmer, recycler, mk2 compressor, mk2 pulverizer, mk2 electric furnace, mk2 solid infuser

**Flux container mk2 output:** -> 3 lifts and 3 screens

After deleting indrev from the server and restarting it, it removed everything related to it from the world as expected.
Once I added the mod again and returned everything back in to their original places, the crash happened again.
The flux container seems to be being corrupted somehow, or perhaps it's somehow acquiring negative charge?

The wire network does not connect to any modded items besides the lifts and screens from the Lifts mod.
The lazuli flux container mk3 mentioned in the log has no modded items connected to its output.

Log: https://pastebin.com/97FugVYw

**Comment by Alumniminium** [comment] 2022-04-09 15:18
`net.minecraft.class_148: Ticking block entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zpm000$modifiedRunLoop(MinecraftServer.java:4856) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.IllegalArgumentException: Amount may not be negative, but it is: -384
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50) ~[fabric-transfer-api-v1-1.5.9+d7c144a865-cdab3dfa62ac4225.jar:?]
        at me.steven.indrev.IREnergyStorage$SideStorage.extract(IREnergyStorage.java:98) ~[indrev-1.13.8-BETA.jar:?]
        at team.reborn.energy.api.EnergyStorageUtil.move(EnergyStorageUtil.java:42) ~[team_reborn_energy-2.0.0-beta1-a90c99d8af2f3ca2.jar:?]
        at me.steven.indrev.utils.MachineinteractionsKt.transferEnergy(machineinteractions.kt:133) ~[indrev-1.13.8-BETA.jar:?]
        at me.steven.indrev.blockentities.MachineBlockEntity.tick(MachineBlockEntity.kt:108) ~[indrev-1.13.8-BETA.jar:?]
        at me.steven.indrev.blocks.machine.MachineBlock.getTicker$lambda-1(MachineBlock.kt:70) ~[indrev-1.13.8-BETA.jar:?]
        at net.minecraft.class_2818$class_5563.redirect$zpp000$checkProcessTEs(class_2818.java:783) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18471(class_1937.java:477) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:365) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$bgo000$fixUpdateSuppressionCrashTick(MinecraftServer.java:5750) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
        ... 6 more`

I think I might have the same bug. 1.8.1

**Comment by ZestyBlaze** [comment] 2022-04-10 16:01
Try updating to a newer version. 1.8.1 is a very old version, even if using 1.16.5 then there are newer versions for it available

**Comment by GabrielOlvH** [comment] 2022-04-19 18:34
Thanks for reporting, this will be fixed in the next update which will be available on CurseForge soon.

**Closed by GabrielOlvH** 2022-04-19 18:34 UTC
Labels: bug
